name: Check Package Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Compare package.json versions
        run: |
          # Fetch and read the version from the PR branch
          PR_VERSION=$(jq -r '.version' package.json)
          echo "PR version: $PR_VERSION"

          # Fetch and read the version from the main branch
          git fetch origin main
          MAIN_VERSION=$(git show origin/main:package.json | jq -r '.version')
          echo "Main branch version: $MAIN_VERSION"

          # Compare versions
          if [ "$PR_VERSION" == "$MAIN_VERSION" ]; then
            echo "Version in package.json is the same as main branch: $PR_VERSION. Please update it for the new release."
            exit 1
          else
            echo "Version in package.json differs from main branch."
          fi
