name: Check Package Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v3

      # Step 2: Read version from PR branch
      - name: Read version from PR branch
        id: pr_version
        run: |
          PR_VERSION=$(jq -r '.version' package.json)
          echo "PR version: $PR_VERSION"
          echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT

      # Step 3: Fetch and check out the main branch
      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout origin/main

      # Step 4: Read version from main branch
      - name: Read version from main branch
        id: main_version
        run: |
          MAIN_VERSION=$(jq -r '.version' package.json)
          echo "Main branch version: $MAIN_VERSION"
          echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT

      # Step 5: Compare versions
      - name: Compare versions
        run: |
          if [ "${{ steps.pr_version.outputs.pr_version }}" == "${{ steps.main_version.outputs.main_version }}" ]; then
            echo "Version in package.json is the same as main branch: ${{ steps.pr_version.outputs.pr_version }}. Please update it for the new release."
            exit 1
          else
            echo "Version in package.json differs from main branch."
          fi
