name: Check Package Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Read version from PR branch
        id: pr_version
        run: |
          PR_VERSION=$(jq -r '.version' package.json)
          echo "PR version: $PR_VERSION"
          echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT

      - name: Read version from main branch
        id: main_version
        run: |
          git fetch origin main
          git checkout origin/main
          MAIN_VERSION=$(jq -r '.version' package.json)
          echo "Main branch version: $MAIN_VERSION"
          echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          PR_VERSION="${{ steps.pr_version.outputs.pr_version }}"
          MAIN_VERSION="${{ steps.main_version.outputs.main_version }}"

          # Compare versions using sort -V
          if [ "$(printf '%s\n%s' \"$MAIN_VERSION\" \"$PR_VERSION\" | sort -V | head -n 1)" == "$PR_VERSION" ]; then
            echo "Version in package.json is not greater than the main branch version: $MAIN_VERSION."
            echo "Please increment the version for the new release."
            exit 1
          else
            echo "Version in package.json ($PR_VERSION) is greater than main branch version ($MAIN_VERSION)."
          fi
